package com.hm.module.homemaking.service;

import com.hm.framework.security.core.LoginUser;
import com.hm.framework.tenant.core.context.TenantContextHolder;
import com.hm.module.homemaking.dal.HmRepository;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import javax.sql.DataSource;
import java.time.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

@SpringJUnitConfig(BusinessIsolationTest.Config.class)
class AftersaleFlowTest {
    @Autowired JdbcTemplate jdbc;@Autowired DataSource dataSource;@Autowired OrderService orders;@Autowired AftersaleService aftersales;@Autowired WorkerService workers;@Autowired CompletionConfirmationService completion;@Autowired PaymentService payments;
    long order;
    @BeforeEach void seed(){var fixture=new BusinessIsolationTest();fixture.jdbc=jdbc;fixture.dataSource=dataSource;fixture.seed();
        jdbc.update("INSERT INTO hm_worker(id,tenant_id,store_id,name) VALUES(3,1,1,'Relief worker')");jdbc.update("INSERT INTO hm_worker_skill VALUES(1,3,1)");jdbc.update("INSERT INTO hm_worker_area VALUES(1,3,'*')");jdbc.update("INSERT INTO hm_worker_schedule(tenant_id,worker_id,starts_at,ends_at) VALUES(1,3,?,?)",LocalDate.now().plusDays(2).atStartOfDay(),LocalDate.now().plusDays(2).atTime(23,30));jdbc.update("INSERT INTO hm_worker_account VALUES(1,3,11)");
        customer(1,1);order=orders.book(new OrderService.Book(1L,1L,LocalDate.now().plusDays(2).atTime(9,0),1L,"aftersale-order"));jdbc.update("UPDATE hm_order SET paid_cents=price_cents,status='COMPLETED',fulfillment_status='COMPLETED',completed_at=CURRENT_TIMESTAMP WHERE id=?",order);}
    @AfterEach void clear(){SecurityContextHolder.clearContext();TenantContextHolder.clear();}
    void customer(long tenant,long id){TenantContextHolder.setTenantId(tenant);TenantContextHolder.setIgnore(false);var u=new LoginUser();u.setId(id);u.setTenantId(tenant);u.setUserType(1);SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(u,null,List.of()));}
    void worker(){TenantContextHolder.setTenantId(1L);TenantContextHolder.setIgnore(false);var u=new LoginUser();u.setId(11L);u.setTenantId(1L);u.setUserType(2);SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(u,null,List.of()));}
    long apply(String type,Integer amount,String key){customer(1,1);return aftersales.apply(new AftersaleService.Request(order,type,amount,"Service issue",key));}

    @Test void allSixRequestTypesAreRepresentedWithoutFakeMoney(){for(String type:List.of("REWORK","REASSIGN_WORKER","REVISIT","OTHER_COMPENSATION")){long id=apply(type,null,"type-"+type);assertNull(jdbc.queryForMap("SELECT * FROM hm_aftersale WHERE id=?",id).get("amount_cents"));aftersales.cancel(id,new AftersaleService.Resolve("Changed mind"));}long partial=apply("PARTIAL_REFUND",1000,"type-partial");assertEquals(1000,jdbc.queryForObject("SELECT amount_cents FROM hm_aftersale WHERE id=?",Integer.class,partial));aftersales.cancel(partial,new AftersaleService.Resolve("Changed mind"));long full=apply("FULL_REFUND",null,"type-full");assertEquals(10000,jdbc.queryForObject("SELECT amount_cents FROM hm_aftersale WHERE id=?",Integer.class,full));}
    @Test void partialMustBeStrictlyPartialAndRequestIsIdempotent(){assertThrows(Exception.class,()->apply("PARTIAL_REFUND",10000,"bad-full"));assertThrows(Exception.class,()->apply("PARTIAL_REFUND",0,"bad-zero"));long id=apply("PARTIAL_REFUND",2500,"same-key");assertEquals(id,apply("PARTIAL_REFUND",2500,"same-key"));assertEquals(1L,jdbc.queryForObject("SELECT COUNT(*) FROM hm_aftersale WHERE request_key='same-key'",Long.class));}
    @Test void onlyOwnerCanReadOrCancel(){long id=apply("REWORK",null,"ownership");customer(1,2);assertThrows(Exception.class,()->aftersales.customerDetail(id));assertThrows(Exception.class,()->aftersales.cancel(id,new AftersaleService.Resolve("Not mine")));customer(2,2);assertThrows(Exception.class,()->aftersales.adminDetail(id));customer(1,1);aftersales.cancel(id,new AftersaleService.Resolve("No longer needed"));assertEquals("CANCELLED",jdbc.queryForObject("SELECT status FROM hm_aftersale WHERE id=?",String.class,id));}
    @Test void compensationRequiresRecordedResolutionAndLeavesMoneyUntouched(){long id=apply("OTHER_COMPENSATION",null,"compensation");aftersales.resolve(id,new AftersaleService.Resolve("Issued a documented service credit"));var row=jdbc.queryForMap("SELECT * FROM hm_aftersale WHERE id=?",id);assertEquals("COMPLETED",row.get("status"));assertNotNull(row.get("closed_at"));assertEquals(0,jdbc.queryForObject("SELECT refunded_cents FROM hm_order WHERE id=?",Integer.class,order));assertEquals(2L,jdbc.queryForObject("SELECT COUNT(*) FROM hm_aftersale_log WHERE aftersale_id=?",Long.class,id));}
    @Test void reassignCreatesCapacityCheckedBookingAndPreservesOldBooking(){long old=jdbc.queryForObject("SELECT booking_id FROM hm_order WHERE id=?",Long.class,order);long id=apply("REASSIGN_WORKER",null,"reassign");LocalDateTime start=LocalDate.now().plusDays(2).atTime(10,0);aftersales.schedule(id,new AftersaleService.Schedule(start,3L,"A different worker will revisit"));var a=jdbc.queryForMap("SELECT * FROM hm_aftersale WHERE id=?",id);long replacement=((Number)a.get("remedy_booking_id")).longValue();assertEquals("SCHEDULED",a.get("status"));assertEquals(3L,a.get("assigned_worker_id"));assertNotEquals(old,replacement);assertEquals("AFTERSALE_REPLACED",jdbc.queryForObject("SELECT status FROM hm_booking WHERE id=?",String.class,old));assertEquals(2L,jdbc.queryForObject("SELECT COUNT(*) FROM hm_worker_slot WHERE booking_id=?",Long.class,replacement));assertEquals(replacement,jdbc.queryForObject("SELECT booking_id FROM hm_order WHERE id=?",Long.class,order));}
    @Test void reassignRejectsSameWorkerAndScheduleConflicts(){long id=apply("REASSIGN_WORKER",null,"same-worker");assertThrows(Exception.class,()->aftersales.schedule(id,new AftersaleService.Schedule(LocalDate.now().plusDays(2).atTime(10,0),1L,"Must change worker")));}
    @Test void remedyRunsThroughWorkerAndCustomerConfirmationBeforeClosing(){long id=apply("REWORK",null,"full-remedy");LocalDateTime planned=LocalDate.now().plusDays(2).atTime(11,0);aftersales.schedule(id,new AftersaleService.Schedule(planned,3L,"Redo the affected work"));long booking=jdbc.queryForObject("SELECT remedy_booking_id FROM hm_aftersale WHERE id=?",Long.class,id);LocalDateTime now=LocalDateTime.now().withSecond(0).withNano(0);jdbc.update("UPDATE hm_booking SET starts_at=?,ends_at=? WHERE id=?",now.minusMinutes(10),now.plusMinutes(50),booking);worker();workers.action(order,new WorkerService.Action("ACCEPT","Accepted remedy"));workers.action(order,new WorkerService.Action("ARRIVE","Arrived"));jdbc.update("INSERT INTO hm_fulfillment_evidence(tenant_id,order_id,worker_id,storage_key,content_type,phase,note) VALUES(1,?,3,'remedy-before','image/jpeg','BEFORE','before')",order);workers.action(order,new WorkerService.Action("START","Started"));assertEquals("IN_PROGRESS",jdbc.queryForObject("SELECT status FROM hm_aftersale WHERE id=?",String.class,id));jdbc.update("INSERT INTO hm_fulfillment_evidence(tenant_id,order_id,worker_id,storage_key,content_type,phase,note) VALUES(1,?,3,'remedy-after','image/jpeg','AFTER','after')",order);workers.action(order,new WorkerService.Action("COMPLETE","Submitted"));assertEquals("AWAITING_CONFIRMATION",jdbc.queryForObject("SELECT status FROM hm_aftersale WHERE id=?",String.class,id));customer(1,1);completion.confirmByCustomer(order);assertEquals("COMPLETED",jdbc.queryForObject("SELECT status FROM hm_aftersale WHERE id=?",String.class,id));assertNotNull(jdbc.queryForObject("SELECT closed_at FROM hm_aftersale WHERE id=?",LocalDateTime.class,id));assertEquals(1L,jdbc.queryForObject("SELECT COUNT(*) FROM hm_settlement WHERE order_id=?",Long.class,order));}
    @Test void refundAndServiceActionsCannotBeMixed(){long refund=apply("PARTIAL_REFUND",1000,"refund-kind");assertThrows(Exception.class,()->aftersales.schedule(refund,new AftersaleService.Schedule(LocalDate.now().plusDays(2).atTime(10,0),3L,"Wrong operation")));aftersales.cancel(refund,new AftersaleService.Resolve("Close"));long service=apply("REVISIT",null,"service-kind");assertThrows(Exception.class,()->aftersales.resolve(service,new AftersaleService.Resolve("Wrong operation")));}
    @Test void failedOnlineRefundRequiresAuditedRetryAndUsesNewAttempt(){long id=apply("PARTIAL_REFUND",1000,"retry-refund");jdbc.update("UPDATE hm_order SET payment_method='ONLINE',pay_order_id=9 WHERE id=?",order);jdbc.update("UPDATE hm_aftersale SET status='FAILED',pay_refund_id=19 WHERE id=?",id);payments.retryRefund(id,"Provider confirms original attempt failed");var row=jdbc.queryForMap("SELECT * FROM hm_aftersale WHERE id=?",id);assertEquals("REQUESTED",row.get("status"));assertNull(row.get("pay_refund_id"));assertEquals(1,((Number)row.get("refund_attempt")).intValue());assertEquals("Provider confirms original attempt failed",row.get("audit_remark"));assertEquals(1L,jdbc.queryForObject("SELECT COUNT(*) FROM hm_aftersale_log WHERE aftersale_id=? AND action='REFUND_RETRIED'",Long.class,id));assertThrows(Exception.class,()->payments.retryRefund(id,"Duplicate retry"));}
}
