// Keep the single-file installer identical to the established upgrade sequence.
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '../..')
const sqlRoot = path.join(root, 'sql/mysql')
const upgrades = fs.readdirSync(path.join(sqlRoot, 'upgrades'))
  .filter(name => /^V\d{3}__.+\.sql$/.test(name)).sort()
for (let i = 0; i < upgrades.length; i++) {
  if (Number(upgrades[i].slice(1, 4)) !== i + 2) {
    throw new Error('Expected consecutive upgrades starting at V002; review the installer sequence.')
  }
}
const sources = ['hm-base.sql', 'hm-pay-mp.sql', 'hm-bootstrap.sql', 'hm-homemaking.sql', 'hm-menu.sql',
  ...upgrades.map(name => `upgrades/${name}`)]
const normalize = text => text.replace(/^\uFEFF/, '').replace(/\r\n/g, '\n')
const latest = upgrades.at(-1)?.slice(0, 4) || 'base'
const header = `-- HM fresh installation, including all upgrades through ${latest}.
-- Import this file ONCE into an EMPTY MySQL 8.0.16+ database; stop on the first error.
-- Do not import the component SQL files or included upgrades again afterward.
-- Existing installations must use only their pending upgrades, never this file.
-- Generated by: node tools/migration/build-init.cjs
-- Verify synchronization: node tools/migration/build-init.cjs --check
-- No database name or production credentials are embedded; select the database in your client.
-- Source attribution and license notices are retained in the repository.
`
const expected = header + sources.map(name =>
  `\n-- ===== sql/mysql/${name} =====\n${normalize(fs.readFileSync(path.join(sqlRoot, name), 'utf8')).trimEnd()}\n`
).join('')
const target = path.join(sqlRoot, 'hm-init.sql')
if (process.argv.includes('--check')) {
  if (!fs.existsSync(target) || normalize(fs.readFileSync(target, 'utf8')) !== expected) {
    throw new Error('hm-init.sql is missing or stale. Run node tools/migration/build-init.cjs and commit the updated installer.')
  }
  console.log(`PASS: hm-init.sql matches all ${sources.length} components through ${latest}.`)
} else {
  fs.writeFileSync(target, expected, 'utf8')
  console.log(`Generated sql/mysql/hm-init.sql through ${latest}; one import for a fresh database.`)
}
