-- Fresh destination only; source hm_legacy_snapshot must be a secured read-only backup.
-- Headquarters tenant 1; verify organization mapping and run without mysql --force.
CREATE TEMPORARY TABLE hm_migration_assertion (ok INT NOT NULL CHECK(ok=1));
START TRANSACTION;
-- Batch execution must abort on first error; never use mysql --force.
INSERT INTO hm_migration_assertion SELECT CASE WHEN (SELECT COUNT(*) FROM hm_customer)=0 AND (SELECT COUNT(*) FROM hm_order)=0 AND (SELECT COUNT(*) FROM hm_store)=0 THEN 1 ELSE 0 END;
INSERT INTO hm_migration_assertion SELECT CASE WHEN COUNT(*)=0 THEN 1 ELSE 0 END FROM hm_legacy_snapshot.hm_order o LEFT JOIN hm_legacy_snapshot.hm_customer_user c ON c.customer_id=o.customer_id LEFT JOIN hm_legacy_snapshot.hm_service_item s ON s.service_item_id=o.service_item_id WHERE c.customer_id IS NULL OR s.service_item_id IS NULL OR o.pay_amount<0 OR o.pay_amount>1000000 OR o.appointment_time_slot NOT REGEXP '^[0-2][0-9]:[03]0-[0-2][0-9]:[03]0$';
INSERT INTO hm_migration_assertion SELECT CASE WHEN COUNT(*)=0 THEN 1 ELSE 0 END FROM (SELECT order_id FROM hm_legacy_snapshot.hm_review WHERE status='0' GROUP BY order_id HAVING COUNT(*)>1) duplicates;
INSERT INTO hm_migration_assertion SELECT CASE WHEN COUNT(*)=0 THEN 1 ELSE 0 END FROM hm_legacy_snapshot.hm_customer_address a LEFT JOIN hm_legacy_snapshot.hm_customer_user c ON c.customer_id=a.customer_id WHERE c.customer_id IS NULL;
INSERT INTO hm_migration_assertion SELECT CASE WHEN COUNT(*)=0 THEN 1 ELSE 0 END FROM hm_legacy_snapshot.hm_order_assign a LEFT JOIN hm_legacy_snapshot.hm_worker_profile w ON w.worker_profile_id=a.worker_id LEFT JOIN hm_legacy_snapshot.sys_user u ON u.user_id=w.user_id WHERE a.assign_status<>'0' AND (w.worker_profile_id IS NULL OR u.user_id IS NULL);
INSERT INTO hm_migration_assertion SELECT CASE WHEN COUNT(*)=0 THEN 1 ELSE 0 END FROM hm_legacy_snapshot.hm_order WHERE RIGHT(appointment_time_slot,5)<=LEFT(appointment_time_slot,5);
INSERT INTO hm_migration_assertion SELECT CASE WHEN COUNT(*)=0 THEN 1 ELSE 0 END FROM (SELECT r.order_id,SUM(r.refund_amount) refunded,MAX(o.pay_amount) paid FROM hm_legacy_snapshot.hm_order_refund r JOIN hm_legacy_snapshot.hm_order o ON o.order_id=r.order_id WHERE r.finish_time IS NOT NULL GROUP BY r.order_id HAVING refunded>paid) invalid_refunds;
-- Archive source business fields for audit and subsequent migration. Session secrets remain only in the secured original backup.
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_user_auth',CAST(auth_id AS CHAR),1,JSON_OBJECT('auth_id',auth_id,'user_id',user_id,'customer_id',customer_id,'auth_type',auth_type,'auth_key',auth_key,'unionid',unionid,'mobile',mobile,'status',status,'create_time',create_time,'update_time',update_time) FROM hm_legacy_snapshot.hm_user_auth;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_customer_user',CAST(customer_id AS CHAR),1,JSON_OBJECT('customer_id',customer_id,'user_id',user_id,'mobile',mobile,'nickname',nickname,'avatar',avatar,'gender',gender,'real_name',real_name,'status',status,'source_channel',source_channel,'org_id',org_id,'last_login_ip',last_login_ip,'last_login_time',last_login_time,'create_by',create_by,'create_time',create_time,'update_by',update_by,'update_time',update_time,'remark',remark) FROM hm_legacy_snapshot.hm_customer_user;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_customer_address',CAST(address_id AS CHAR),1,JSON_OBJECT('address_id',address_id,'customer_id',customer_id,'contact_name',contact_name,'contact_mobile',contact_mobile,'province_code',province_code,'province_name',province_name,'city_code',city_code,'city_name',city_name,'district_code',district_code,'district_name',district_name,'detail_address',detail_address,'longitude',longitude,'latitude',latitude,'is_default',is_default,'create_time',create_time,'update_time',update_time) FROM hm_legacy_snapshot.hm_customer_address;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_org',CAST(org_id AS CHAR),1,JSON_OBJECT('org_id',org_id,'parent_org_id',parent_org_id,'org_name',org_name,'org_type',org_type,'contact_name',contact_name,'contact_mobile',contact_mobile,'province_code',province_code,'city_code',city_code,'district_code',district_code,'status',status,'create_by',create_by,'create_time',create_time,'update_by',update_by,'update_time',update_time,'remark',remark) FROM hm_legacy_snapshot.hm_org;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_service_category',CAST(category_id AS CHAR),1,JSON_OBJECT('category_id',category_id,'parent_id',parent_id,'category_name',category_name,'category_icon',category_icon,'banner_image',banner_image,'banner_image_storage',banner_image_storage,'banner_image_object_key',banner_image_object_key,'sort_no',sort_no,'show_in_miniapp',show_in_miniapp,'show_in_portal',show_in_portal,'status',status,'del_flag',del_flag,'create_by',create_by,'create_time',create_time,'update_by',update_by,'update_time',update_time,'remark',remark) FROM hm_legacy_snapshot.hm_service_category;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_service_item',CAST(service_item_id AS CHAR),1,JSON_OBJECT('service_item_id',service_item_id,'category_id',category_id,'service_name',service_name,'org_id',org_id,'service_sub_title',service_sub_title,'service_cover',service_cover,'service_cover_storage',service_cover_storage,'service_cover_object_key',service_cover_object_key,'service_desc',service_desc,'service_content',service_content,'service_duration',service_duration,'sale_type',sale_type,'base_price',base_price,'unit_name',unit_name,'need_manual_confirm',need_manual_confirm,'allow_assign_worker',allow_assign_worker,'show_in_miniapp',show_in_miniapp,'show_in_portal',show_in_portal,'status',status,'del_flag',del_flag,'create_by',create_by,'create_time',create_time,'update_by',update_by,'update_time',update_time,'remark',remark) FROM hm_legacy_snapshot.hm_service_item;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_service_sku',CAST(sku_id AS CHAR),1,JSON_OBJECT('sku_id',sku_id,'service_item_id',service_item_id,'sku_name',sku_name,'price',price,'original_price',original_price,'duration_minute',duration_minute,'sort_no',sort_no,'status',status) FROM hm_legacy_snapshot.hm_service_sku;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_service_extra_item',CAST(extra_item_id AS CHAR),1,JSON_OBJECT('extra_item_id',extra_item_id,'service_item_id',service_item_id,'extra_name',extra_name,'extra_price',extra_price,'charge_type',charge_type,'sort_no',sort_no,'status',status) FROM hm_legacy_snapshot.hm_service_extra_item;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_service_area',CAST(area_id AS CHAR),1,JSON_OBJECT('area_id',area_id,'province_code',province_code,'province_name',province_name,'city_code',city_code,'city_name',city_name,'district_code',district_code,'district_name',district_name,'area_name',area_name,'org_id',org_id,'extra_fee',extra_fee,'status',status) FROM hm_legacy_snapshot.hm_service_area;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_service_item_area_rel',CAST(id AS CHAR),1,JSON_OBJECT('id',id,'service_item_id',service_item_id,'area_id',area_id) FROM hm_legacy_snapshot.hm_service_item_area_rel;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_booking_rule',CAST(rule_id AS CHAR),1,JSON_OBJECT('rule_id',rule_id,'service_item_id',service_item_id,'advance_days',advance_days,'min_advance_minutes',min_advance_minutes,'max_advance_days',max_advance_days,'allow_same_day',allow_same_day,'time_slots_json',time_slots_json,'cancel_rule_json',cancel_rule_json,'status',status) FROM hm_legacy_snapshot.hm_booking_rule;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_worker_profile',CAST(worker_profile_id AS CHAR),1,JSON_OBJECT('worker_profile_id',worker_profile_id,'user_id',user_id,'id_card_no',id_card_no,'worker_type',worker_type,'intro',intro,'service_star',service_star,'service_count',service_count,'employment_status',employment_status,'work_status',work_status,'org_id',org_id,'status',status,'create_by',create_by,'create_time',create_time,'update_by',update_by,'update_time',update_time,'remark',remark) FROM hm_legacy_snapshot.hm_worker_profile;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_worker_service_rel',CAST(id AS CHAR),1,JSON_OBJECT('id',id,'worker_id',worker_id,'service_item_id',service_item_id) FROM hm_legacy_snapshot.hm_worker_service_rel;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_worker_area_rel',CAST(id AS CHAR),1,JSON_OBJECT('id',id,'worker_id',worker_id,'area_id',area_id) FROM hm_legacy_snapshot.hm_worker_area_rel;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_worker_schedule',CAST(schedule_id AS CHAR),1,JSON_OBJECT('schedule_id',schedule_id,'worker_id',worker_id,'work_date',work_date,'start_time',start_time,'end_time',end_time,'schedule_status',schedule_status) FROM hm_legacy_snapshot.hm_worker_schedule;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_order',CAST(order_id AS CHAR),1,JSON_OBJECT('order_id',order_id,'order_no',order_no,'customer_id',customer_id,'org_id',org_id,'service_item_id',service_item_id,'sku_id',sku_id,'order_type',order_type,'order_status',order_status,'pay_status',pay_status,'assign_status',assign_status,'contact_name',contact_name,'contact_mobile',contact_mobile,'service_address',service_address,'province_code',province_code,'city_code',city_code,'district_code',district_code,'appointment_date',appointment_date,'appointment_time_slot',appointment_time_slot,'service_start_time',service_start_time,'service_end_time',service_end_time,'base_amount',base_amount,'extra_amount',extra_amount,'discount_amount',discount_amount,'pay_amount',pay_amount,'pay_time',pay_time,'pay_channel',pay_channel,'source_channel',source_channel,'customer_remark',customer_remark,'cancel_reason',cancel_reason,'create_time',create_time,'update_time',update_time) FROM hm_legacy_snapshot.hm_order;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_order_item',CAST(order_item_id AS CHAR),1,JSON_OBJECT('order_item_id',order_item_id,'order_id',order_id,'service_item_id',service_item_id,'sku_id',sku_id,'item_name',item_name,'item_price',item_price,'quantity',quantity,'item_amount',item_amount) FROM hm_legacy_snapshot.hm_order_item;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_order_assign',CAST(assign_id AS CHAR),1,JSON_OBJECT('assign_id',assign_id,'order_id',order_id,'worker_id',worker_id,'assign_status',assign_status,'assign_time',assign_time,'accept_time',accept_time,'finish_time',finish_time,'cancel_time',cancel_time,'remark',remark) FROM hm_legacy_snapshot.hm_order_assign;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_order_operate_log',CAST(log_id AS CHAR),1,JSON_OBJECT('log_id',log_id,'order_id',order_id,'operator_type',operator_type,'operator_id',operator_id,'operator_name',operator_name,'action_type',action_type,'action_desc',action_desc,'create_time',create_time) FROM hm_legacy_snapshot.hm_order_operate_log;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_order_refund',CAST(refund_id AS CHAR),1,JSON_OBJECT('refund_id',refund_id,'order_id',order_id,'refund_no',refund_no,'refund_status',refund_status,'refund_amount',refund_amount,'refund_reason',refund_reason,'apply_time',apply_time,'audit_time',audit_time,'finish_time',finish_time) FROM hm_legacy_snapshot.hm_order_refund;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_review',CAST(review_id AS CHAR),1,JSON_OBJECT('review_id',review_id,'order_id',order_id,'customer_id',customer_id,'worker_id',worker_id,'score',score,'tags_json',tags_json,'content',content,'images_json',images_json,'is_anonymous',is_anonymous,'status',status,'create_time',create_time) FROM hm_legacy_snapshot.hm_review;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_portal_content',CAST(content_id AS CHAR),1,JSON_OBJECT('content_id',content_id,'content_type',content_type,'title',title,'sub_title',sub_title,'cover_image',cover_image,'cover_image_storage',cover_image_storage,'cover_image_object_key',cover_image_object_key,'summary',summary,'content_html',content_html,'sort_no',sort_no,'publish_status',publish_status,'publish_time',publish_time,'create_by',create_by,'create_time',create_time,'update_by',update_by,'update_time',update_time) FROM hm_legacy_snapshot.hm_portal_content;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_mini_nav_config',CAST(nav_id AS CHAR),1,JSON_OBJECT('nav_id',nav_id,'org_id',org_id,'nav_name',nav_name,'nav_icon',nav_icon,'nav_path',nav_path,'sort_no',sort_no,'status',status) FROM hm_legacy_snapshot.hm_mini_nav_config;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_mini_home_config',CAST(config_id AS CHAR),1,JSON_OBJECT('config_id',config_id,'org_id',org_id,'config_key',config_key,'config_value',config_value,'status',status) FROM hm_legacy_snapshot.hm_mini_home_config;
INSERT INTO hm_legacy_archive(source_table,source_id,tenant_id,payload) SELECT 'hm_lead',CAST(lead_id AS CHAR),1,JSON_OBJECT('lead_id',lead_id,'lead_type',lead_type,'name',name,'mobile',mobile,'city_name',city_name,'org_id',org_id,'intent_service',intent_service,'content',content,'source_channel',source_channel,'follow_status',follow_status,'follow_by',follow_by,'follow_time',follow_time,'create_time',create_time,'update_time',update_time) FROM hm_legacy_snapshot.hm_lead;

INSERT INTO hm_customer(id,mobile,nickname,avatar,status,created_at)
 SELECT customer_id,mobile,COALESCE(nickname,''),COALESCE(avatar,''),CASE status WHEN '0' THEN 'ACTIVE' ELSE 'INACTIVE' END,COALESCE(create_time,CURRENT_TIMESTAMP)
 FROM hm_legacy_snapshot.hm_customer_user;
INSERT INTO hm_customer_tenant(tenant_id,customer_id,status,source,created_at)
 SELECT 1,customer_id,CASE status WHEN '0' THEN 'ACTIVE' ELSE 'INACTIVE' END,COALESCE(source_channel,'LEGACY'),COALESCE(create_time,CURRENT_TIMESTAMP) FROM hm_legacy_snapshot.hm_customer_user;
INSERT INTO hm_store(id,tenant_id,name,address,phone,status)
 SELECT org_id,1,org_name,'',COALESCE(contact_mobile,''),CASE status WHEN '0' THEN 'ACTIVE' ELSE 'INACTIVE' END FROM hm_legacy_snapshot.hm_org;
INSERT INTO hm_store(id,tenant_id,name) SELECT 1,1,'总部直营门店' WHERE NOT EXISTS(SELECT 1 FROM hm_store WHERE id=1);
INSERT INTO hm_worker(id,tenant_id,store_id,name,phone,skills,avatar,status)
 SELECT w.worker_profile_id,1,COALESCE(s.id,1),COALESCE(u.nick_name,u.user_name),COALESCE(u.phonenumber,''),COALESCE(w.intro,''),COALESCE(u.avatar,''),CASE w.status WHEN '0' THEN 'ACTIVE' ELSE 'INACTIVE' END
 FROM hm_legacy_snapshot.hm_worker_profile w JOIN hm_legacy_snapshot.sys_user u ON u.user_id=w.user_id LEFT JOIN hm_store s ON s.id=w.org_id AND s.tenant_id=1;
INSERT INTO hm_service_category(id,tenant_id,name,icon)
 SELECT category_id,1,category_name,COALESCE(category_icon,'') FROM hm_legacy_snapshot.hm_service_category;
INSERT INTO hm_service(id,tenant_id,store_id,name,category,description,price_cents,duration_minutes,cover,status)
 SELECT i.service_item_id,1,COALESCE(s.id,1),i.service_name,COALESCE(c.category_name,'家政服务'),COALESCE(i.service_desc,''),CAST(ROUND(i.base_price*100) AS SIGNED),GREATEST(30,COALESCE(i.service_duration,30)),COALESCE(i.service_cover,''),
 CASE WHEN i.status='0' AND i.del_flag='0' AND i.base_price>0 THEN 'ACTIVE' ELSE 'INACTIVE' END
 FROM hm_legacy_snapshot.hm_service_item i LEFT JOIN hm_legacy_snapshot.hm_service_category c ON c.category_id=i.category_id LEFT JOIN hm_store s ON s.id=i.org_id AND s.tenant_id=1;
INSERT INTO hm_service_sku(id,tenant_id,service_id,name,price_cents,duration_minutes,status)
 SELECT sku_id,1,service_item_id,sku_name,CAST(ROUND(price*100) AS SIGNED),GREATEST(30,COALESCE(duration_minute,30)),CASE WHEN status='0' AND price>0 THEN 'ACTIVE' ELSE 'INACTIVE' END FROM hm_legacy_snapshot.hm_service_sku;
INSERT INTO hm_service_extra(id,tenant_id,service_id,name,price_cents,status)
 SELECT extra_item_id,1,service_item_id,extra_name,CAST(ROUND(extra_price*100) AS SIGNED),CASE status WHEN '0' THEN 'ACTIVE' ELSE 'INACTIVE' END FROM hm_legacy_snapshot.hm_service_extra_item;
INSERT INTO hm_service_area(id,tenant_id,name,district_code,extra_cents,status)
 SELECT area_id,1,area_name,COALESCE(district_code,''),CAST(ROUND(extra_fee*100) AS SIGNED),CASE status WHEN '0' THEN 'ACTIVE' ELSE 'INACTIVE' END FROM hm_legacy_snapshot.hm_service_area;
INSERT INTO hm_service_area_relation(tenant_id,service_id,area_id) SELECT 1,service_item_id,area_id FROM hm_legacy_snapshot.hm_service_item_area_rel;
INSERT INTO hm_service_booking_rule(tenant_id,service_id,min_advance_minutes,max_advance_days,allow_same_day,time_slots_json,cancel_rule_json)
 SELECT 1,service_item_id,GREATEST(0,min_advance_minutes),GREATEST(1,max_advance_days),allow_same_day='1',time_slots_json,cancel_rule_json FROM hm_legacy_snapshot.hm_booking_rule WHERE status='0';
INSERT INTO hm_customer_address(id,tenant_id,customer_id,contact_name,phone,address,district_code,is_default)
 SELECT address_id,1,customer_id,contact_name,contact_mobile,CONCAT(COALESCE(province_name,''),COALESCE(city_name,''),COALESCE(district_name,''),detail_address),COALESCE(district_code,''),is_default='1' FROM hm_legacy_snapshot.hm_customer_address;
INSERT INTO hm_booking(id,tenant_id,customer_id,service_id,store_id,starts_at,ends_at,status,created_at)
 SELECT o.order_id,1,o.customer_id,o.service_item_id,COALESCE(s.id,1),
 CAST(CONCAT(o.appointment_date,' ',LEFT(o.appointment_time_slot,5),':00') AS DATETIME),
 CAST(CONCAT(o.appointment_date,' ',RIGHT(o.appointment_time_slot,5),':00') AS DATETIME),
 CASE WHEN o.order_status IN ('60','70') THEN 'COMPLETED' WHEN o.order_status IN ('80','90') THEN 'CANCELLED' ELSE 'RESERVED' END,COALESCE(o.create_time,CURRENT_TIMESTAMP)
 FROM hm_legacy_snapshot.hm_order o LEFT JOIN hm_legacy_snapshot.hm_service_item i ON i.service_item_id=o.service_item_id LEFT JOIN hm_store s ON s.id=o.org_id AND s.tenant_id=1;
INSERT INTO hm_order(id,tenant_id,customer_id,booking_id,service_id,service_name,store_id,price_cents,paid_cents,refunded_cents,status,contact_name,phone,address,request_key,customer_remark,created_at,paid_at,completed_at)
 SELECT o.order_id,1,o.customer_id,o.order_id,o.service_item_id,COALESCE(i.service_name,'历史服务'),COALESCE(s.id,1),CAST(ROUND(o.pay_amount*100) AS SIGNED),CASE o.pay_status WHEN '1' THEN CAST(ROUND(o.pay_amount*100) AS SIGNED) ELSE 0 END,
 CASE o.order_status WHEN '90' THEN CAST(ROUND(o.pay_amount*100) AS SIGNED) ELSE COALESCE((SELECT CAST(ROUND(SUM(r.refund_amount)*100) AS SIGNED) FROM hm_legacy_snapshot.hm_order_refund r WHERE r.order_id=o.order_id AND r.finish_time IS NOT NULL),0) END,
 CASE WHEN o.order_status IN ('20','30','40','50','60','70') AND o.pay_status<>'1' THEN 'MIGRATION_REVIEW' ELSE CASE o.order_status WHEN '10' THEN 'UNPAID' WHEN '20' THEN 'PAID' WHEN '30' THEN 'PAID' WHEN '40' THEN 'ASSIGNED' WHEN '50' THEN 'IN_SERVICE' WHEN '60' THEN 'COMPLETED' WHEN '70' THEN 'COMPLETED' WHEN '80' THEN 'CANCELLED' WHEN '90' THEN 'REFUNDED' ELSE 'MIGRATION_REVIEW' END END,
 o.contact_name,o.contact_mobile,o.service_address,CONCAT('legacy:',o.order_no),COALESCE(o.customer_remark,''),COALESCE(o.create_time,CURRENT_TIMESTAMP),o.pay_time,o.service_end_time
 FROM hm_legacy_snapshot.hm_order o LEFT JOIN hm_legacy_snapshot.hm_service_item i ON i.service_item_id=o.service_item_id LEFT JOIN hm_store s ON s.id=o.org_id AND s.tenant_id=1;
UPDATE hm_order o JOIN (SELECT order_id,MAX(assign_id) latest FROM hm_legacy_snapshot.hm_order_assign WHERE assign_status<>'0' GROUP BY order_id) x ON x.order_id=o.id
 JOIN hm_legacy_snapshot.hm_order_assign a ON a.assign_id=x.latest SET o.worker_id=a.worker_id WHERE o.tenant_id=1;
UPDATE hm_booking b JOIN hm_order o ON o.booking_id=b.id AND o.tenant_id=b.tenant_id SET b.worker_id=o.worker_id WHERE b.tenant_id=1;
INSERT INTO hm_order_item(id,tenant_id,order_id,name,price_cents,quantity,total_cents)
 SELECT order_item_id,1,order_id,item_name,CAST(ROUND(item_price*100) AS SIGNED),quantity,CAST(ROUND(item_amount*100) AS SIGNED) FROM hm_legacy_snapshot.hm_order_item;
INSERT INTO hm_order_log(id,tenant_id,order_id,action,actor_id,detail,created_at)
 SELECT log_id,1,order_id,action_type,operator_id,COALESCE(action_desc,''),COALESCE(create_time,CURRENT_TIMESTAMP) FROM hm_legacy_snapshot.hm_order_operate_log;
INSERT INTO hm_review(id,tenant_id,customer_id,order_id,rating,content,created_at)
 SELECT review_id,1,customer_id,order_id,score,COALESCE(content,''),COALESCE(create_time,CURRENT_TIMESTAMP) FROM hm_legacy_snapshot.hm_review WHERE status='0';
INSERT INTO hm_aftersale(id,tenant_id,customer_id,order_id,amount_cents,reason,status,created_at)
 SELECT r.refund_id,1,o.customer_id,r.order_id,CAST(ROUND(r.refund_amount*100) AS SIGNED),COALESCE(r.refund_reason,''),CASE WHEN r.finish_time IS NOT NULL THEN 'REFUNDED' ELSE 'MIGRATION_REVIEW' END,COALESCE(r.apply_time,CURRENT_TIMESTAMP)
 FROM hm_legacy_snapshot.hm_order_refund r JOIN hm_legacy_snapshot.hm_order o ON o.order_id=r.order_id WHERE r.refund_amount>0;
INSERT INTO hm_portal_content(id,tenant_id,content_type,title,summary,content_html,cover_image,published)
 SELECT content_id,1,content_type,title,COALESCE(summary,''),content_html,COALESCE(cover_image,''),publish_status='1' FROM hm_legacy_snapshot.hm_portal_content;
INSERT INTO hm_home_content(tenant_id,config_key,config_value) SELECT 1,config_key,config_value FROM hm_legacy_snapshot.hm_mini_home_config WHERE status='0';
-- Rebuild occupied slots; overlapping historical assignments fail instead of permitting double booking.
INSERT INTO hm_worker_slot(tenant_id,worker_id,starts_at,booking_id)
 SELECT b.tenant_id,b.worker_id,TIMESTAMPADD(MINUTE,n.n*30,b.starts_at),b.id FROM hm_booking b
 JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15) n
 ON TIMESTAMPADD(MINUTE,n.n*30,b.starts_at)<b.ends_at
 WHERE b.tenant_id=1 AND b.worker_id IS NOT NULL AND b.status='RESERVED';
COMMIT;
DROP TEMPORARY TABLE hm_migration_assertion;
