-- Enabled pay/mp schema derived from the pinned upstream data objects.
-- The pinned upstream base SQL includes system/infra only. No demo accounts or payment credentials are seeded.

CREATE TABLE `pay_app` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `app_key` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `status` INT NULL,
  `remark` TEXT NULL,
  `order_notify_url` TEXT NULL,
  `refund_notify_url` TEXT NULL,
  `transfer_notify_url` TEXT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_pay_app_tenant` (`tenant_id`),
  UNIQUE KEY `uk_pay_app_key` (`tenant_id`,`app_key`,`deleted`)
);

CREATE TABLE `pay_channel` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `code` VARCHAR(255) NULL,
  `status` INT NULL,
  `fee_rate` DECIMAL(18,6) NULL,
  `remark` TEXT NULL,
  `app_id` BIGINT NULL,
  `config` TEXT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_pay_channel_tenant` (`tenant_id`)
);

CREATE TABLE `pay_demo_order` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `user_id` BIGINT NULL,
  `spu_id` BIGINT NULL,
  `spu_name` TEXT NULL,
  `price` INT NULL,
  `pay_status` BOOLEAN NULL,
  `pay_order_id` BIGINT NULL,
  `pay_time` DATETIME NULL,
  `pay_channel_code` TEXT NULL,
  `pay_refund_id` BIGINT NULL,
  `refund_price` INT NULL,
  `refund_time` DATETIME NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_pay_demo_order_tenant` (`tenant_id`)
);

CREATE TABLE `pay_demo_withdraw` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `subject` TEXT NULL,
  `price` INT NULL,
  `user_account` TEXT NULL,
  `user_name` TEXT NULL,
  `type` INT NULL,
  `status` INT NULL,
  `pay_transfer_id` BIGINT NULL,
  `transfer_channel_code` TEXT NULL,
  `transfer_time` DATETIME NULL,
  `transfer_error_msg` TEXT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_pay_demo_withdraw_tenant` (`tenant_id`)
);

CREATE TABLE `pay_notify_log` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `task_id` BIGINT NULL,
  `notify_times` INT NULL,
  `response` TEXT NULL,
  `status` INT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_pay_notify_log_tenant` (`tenant_id`)
);

CREATE TABLE `pay_notify_task` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `app_id` BIGINT NULL,
  `type` INT NULL,
  `data_id` BIGINT NULL,
  `merchant_order_id` VARCHAR(255) NULL,
  `merchant_refund_id` VARCHAR(255) NULL,
  `merchant_transfer_id` TEXT NULL,
  `status` INT NULL,
  `next_notify_time` DATETIME NULL,
  `last_execute_time` DATETIME NULL,
  `notify_times` INT NULL,
  `max_notify_times` INT NULL,
  `notify_url` TEXT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_pay_notify_task_tenant` (`tenant_id`)
);

CREATE TABLE `pay_order` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `app_id` BIGINT NULL,
  `channel_id` BIGINT NULL,
  `channel_code` TEXT NULL,
  `user_id` BIGINT NULL,
  `user_type` INT NULL,
  `merchant_order_id` VARCHAR(255) NULL,
  `subject` TEXT NULL,
  `body` TEXT NULL,
  `notify_url` TEXT NULL,
  `price` INT NULL,
  `channel_fee_rate` DECIMAL(18,6) NULL,
  `channel_fee_price` INT NULL,
  `status` INT NULL,
  `user_ip` TEXT NULL,
  `expire_time` DATETIME NULL,
  `success_time` DATETIME NULL,
  `extension_id` BIGINT NULL,
  `no` VARCHAR(255) NULL,
  `refund_price` INT NULL,
  `channel_user_id` TEXT NULL,
  `channel_order_no` VARCHAR(255) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_pay_order_tenant` (`tenant_id`)
);

CREATE TABLE `pay_order_extension` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `no` VARCHAR(255) NULL,
  `order_id` BIGINT NULL,
  `channel_id` BIGINT NULL,
  `channel_code` TEXT NULL,
  `user_ip` TEXT NULL,
  `status` INT NULL,
  `channel_extras` TEXT NULL,
  `channel_error_code` TEXT NULL,
  `channel_error_msg` TEXT NULL,
  `channel_notify_data` TEXT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_pay_order_extension_tenant` (`tenant_id`)
);

CREATE TABLE `pay_refund` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `no` VARCHAR(255) NULL,
  `app_id` BIGINT NULL,
  `channel_id` BIGINT NULL,
  `channel_code` TEXT NULL,
  `order_id` BIGINT NULL,
  `order_no` TEXT NULL,
  `user_id` BIGINT NULL,
  `user_type` INT NULL,
  `merchant_order_id` VARCHAR(255) NULL,
  `merchant_refund_id` VARCHAR(255) NULL,
  `notify_url` TEXT NULL,
  `status` INT NULL,
  `pay_price` INT NULL,
  `refund_price` INT NULL,
  `reason` TEXT NULL,
  `user_ip` TEXT NULL,
  `channel_order_no` VARCHAR(255) NULL,
  `channel_refund_no` VARCHAR(255) NULL,
  `success_time` DATETIME NULL,
  `channel_error_code` TEXT NULL,
  `channel_error_msg` TEXT NULL,
  `channel_notify_data` TEXT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_pay_refund_tenant` (`tenant_id`)
);

CREATE TABLE `pay_transfer` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `no` VARCHAR(255) NULL,
  `app_id` BIGINT NULL,
  `channel_id` BIGINT NULL,
  `channel_code` TEXT NULL,
  `user_id` BIGINT NULL,
  `user_type` INT NULL,
  `merchant_transfer_id` TEXT NULL,
  `subject` TEXT NULL,
  `price` INT NULL,
  `user_account` TEXT NULL,
  `user_name` TEXT NULL,
  `status` INT NULL,
  `success_time` DATETIME NULL,
  `notify_url` TEXT NULL,
  `user_ip` TEXT NULL,
  `channel_extras` TEXT NULL,
  `channel_transfer_no` TEXT NULL,
  `channel_error_code` TEXT NULL,
  `channel_error_msg` TEXT NULL,
  `channel_notify_data` TEXT NULL,
  `channel_package_info` TEXT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_pay_transfer_tenant` (`tenant_id`)
);

CREATE TABLE `pay_wallet` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `user_id` BIGINT NULL,
  `user_type` INT NULL,
  `balance` INT NULL,
  `freeze_price` INT NULL,
  `total_expense` INT NULL,
  `total_recharge` INT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_pay_wallet_tenant` (`tenant_id`)
);

CREATE TABLE `pay_wallet_recharge` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `wallet_id` BIGINT NULL,
  `total_price` INT NULL,
  `pay_price` INT NULL,
  `bonus_price` INT NULL,
  `package_id` BIGINT NULL,
  `pay_status` BOOLEAN NULL,
  `pay_order_id` BIGINT NULL,
  `pay_channel_code` TEXT NULL,
  `pay_time` DATETIME NULL,
  `pay_refund_id` BIGINT NULL,
  `refund_total_price` INT NULL,
  `refund_pay_price` INT NULL,
  `refund_bonus_price` INT NULL,
  `refund_time` DATETIME NULL,
  `refund_status` INT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_pay_wallet_recharge_tenant` (`tenant_id`)
);

CREATE TABLE `pay_wallet_recharge_package` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `pay_price` INT NULL,
  `bonus_price` INT NULL,
  `status` INT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_pay_wallet_recharge_package_tenant` (`tenant_id`)
);

CREATE TABLE `pay_wallet_transaction` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `no` VARCHAR(255) NULL,
  `wallet_id` BIGINT NULL,
  `biz_type` INT NULL,
  `biz_id` TEXT NULL,
  `title` TEXT NULL,
  `price` INT NULL,
  `balance` INT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_pay_wallet_transaction_tenant` (`tenant_id`)
);

CREATE TABLE `mp_account` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `account` TEXT NULL,
  `app_id` VARCHAR(255) NULL,
  `app_secret` TEXT NULL,
  `token` TEXT NULL,
  `aes_key` TEXT NULL,
  `qr_code_url` TEXT NULL,
  `remark` TEXT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_mp_account_tenant` (`tenant_id`),
  UNIQUE KEY `uk_mp_app_id` (`app_id`)
);

CREATE TABLE `mp_material` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `account_id` BIGINT NULL,
  `app_id` VARCHAR(255) NULL,
  `media_id` TEXT NULL,
  `type` VARCHAR(255) NULL,
  `permanent` BOOLEAN NULL,
  `url` TEXT NULL,
  `name` VARCHAR(255) NULL,
  `mp_url` TEXT NULL,
  `title` TEXT NULL,
  `introduction` TEXT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_mp_material_tenant` (`tenant_id`)
);

CREATE TABLE `mp_menu` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `account_id` BIGINT NULL,
  `app_id` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `menu_key` TEXT NULL,
  `parent_id` BIGINT NULL,
  `type` VARCHAR(255) NULL,
  `url` TEXT NULL,
  `mini_program_app_id` TEXT NULL,
  `mini_program_page_path` TEXT NULL,
  `article_id` TEXT NULL,
  `reply_message_type` TEXT NULL,
  `reply_content` TEXT NULL,
  `reply_media_id` TEXT NULL,
  `reply_media_url` TEXT NULL,
  `reply_title` TEXT NULL,
  `reply_description` TEXT NULL,
  `reply_thumb_media_id` TEXT NULL,
  `reply_thumb_media_url` TEXT NULL,
  `reply_articles` TEXT NULL,
  `reply_music_url` TEXT NULL,
  `reply_hq_music_url` TEXT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_mp_menu_tenant` (`tenant_id`)
);

CREATE TABLE `mp_auto_reply` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `account_id` BIGINT NULL,
  `app_id` VARCHAR(255) NULL,
  `type` INT NULL,
  `request_keyword` TEXT NULL,
  `request_match` INT NULL,
  `request_message_type` TEXT NULL,
  `response_message_type` TEXT NULL,
  `response_content` TEXT NULL,
  `response_media_id` TEXT NULL,
  `response_media_url` TEXT NULL,
  `response_title` TEXT NULL,
  `response_description` TEXT NULL,
  `response_thumb_media_id` TEXT NULL,
  `response_thumb_media_url` TEXT NULL,
  `response_articles` TEXT NULL,
  `response_music_url` TEXT NULL,
  `response_hq_music_url` TEXT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_mp_auto_reply_tenant` (`tenant_id`)
);

CREATE TABLE `mp_message` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `msg_id` BIGINT NULL,
  `account_id` BIGINT NULL,
  `app_id` VARCHAR(255) NULL,
  `user_id` BIGINT NULL,
  `openid` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `send_from` INT NULL,
  `content` TEXT NULL,
  `media_id` TEXT NULL,
  `media_url` TEXT NULL,
  `recognition` TEXT NULL,
  `format` TEXT NULL,
  `title` TEXT NULL,
  `description` TEXT NULL,
  `thumb_media_id` TEXT NULL,
  `thumb_media_url` TEXT NULL,
  `url` TEXT NULL,
  `location_x` DECIMAL(18,6) NULL,
  `location_y` DECIMAL(18,6) NULL,
  `scale` DECIMAL(18,6) NULL,
  `label` TEXT NULL,
  `articles` TEXT NULL,
  `music_url` TEXT NULL,
  `hq_music_url` TEXT NULL,
  `event` TEXT NULL,
  `event_key` TEXT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_mp_message_tenant` (`tenant_id`)
);

CREATE TABLE `mp_message_template` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `account_id` BIGINT NULL,
  `app_id` VARCHAR(255) NULL,
  `template_id` TEXT NULL,
  `title` TEXT NULL,
  `content` TEXT NULL,
  `example` TEXT NULL,
  `primary_industry` TEXT NULL,
  `deputy_industry` TEXT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_mp_message_template_tenant` (`tenant_id`)
);

CREATE TABLE `mp_tag` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `tag_id` BIGINT NULL,
  `name` VARCHAR(255) NULL,
  `count` INT NULL,
  `account_id` BIGINT NULL,
  `app_id` VARCHAR(255) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_mp_tag_tenant` (`tenant_id`)
);

CREATE TABLE `mp_user` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `openid` VARCHAR(255) NULL,
  `union_id` TEXT NULL,
  `subscribe_status` INT NULL,
  `subscribe_time` DATETIME NULL,
  `unsubscribe_time` DATETIME NULL,
  `nickname` TEXT NULL,
  `head_image_url` TEXT NULL,
  `language` TEXT NULL,
  `country` TEXT NULL,
  `province` TEXT NULL,
  `city` TEXT NULL,
  `remark` TEXT NULL,
  `tag_ids` TEXT NULL,
  `account_id` BIGINT NULL,
  `app_id` VARCHAR(255) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_mp_user_tenant` (`tenant_id`)
);
